name: Deploy Portfolio
# please work
on:
  push:
    branches:
      - main  # Triggers on every push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runs the job on an Ubuntu machine
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # Checks out the latest code in the repo

      - name: Set up SSH
        run: |
          # SSH to server
          ssh -vvv -t tiu@14.200.242.54 << EOF
          
            echo "hi" > helloFromGithub.txt
          
          EOF