name: Deploy Portfolio

on:
  push:
    branches:
      - main  # Triggers on every push to the main branch

jobs:
  deploy:
    runs-on: self-hosted  # Runs the job on your self-hosted runner
    steps:
      - name: Deploy to Raspberry Pi
        run: |
          echo pwd
          cd /home/tiu/portfolio
          git pull origin main  # Update repository
          npm install            # Install dependencies
          npm run build          # Build the project
          npm run host           # Start the server
