name: Deploy Portfolio

on:
  push:
    branches:
      - main  # Triggers on every push to the main branch

jobs:
  deploy:
    runs-on: self-hosted  # Runs the job on your self-hosted runner
    steps:
      - name: Pull from origin main
        run: git pull origin main  # Update repository
          
      - name: Npm install
        run: npm install # Install dependencies

      - name: Npm run build
        run: npm run build  # Build the application
      
      - name: Npm run host
        run: npm run host           # Start the server
