name: Deploy Portfolio
# please work
on:
  push:
    branches:
      - main  # Triggers on every push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runs the job on an Ubuntu machine
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # Checks out the latest code in the repo

      - name: Set up SSH
        run: |
          # Add your private key from GitHub Secrets
          ssh -t tiu@118.209.211.137 'echo "hi" > helloFromGithub.txt'
