name: Deploy Portfolio
# please work
on:
  push:
    branches:
      - main  # Triggers on every push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runs the job on an Ubuntu machine
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # Checks out the latest code in the repo

      - name: Set up SSH
        run: |
          # Add your private key from GitHub Secrets
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          
          # Add the remote server to known hosts to avoid host checking prompts
          ssh-keyscan -H 118.209.211.137 >> ~/.ssh/known_hosts
          
          # Test SSH connection
          ssh -i private_key.pem tiu@118.209.211.137 'echo "Connected to the server!"'
